security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        # Firewall pour les employés
        employee_admin:
            pattern: ^/employe_admin
            provider: app_user_provider
            form_login:
                login_path: employe_login
                check_path: employe_login
            logout:
                path: employe_logout
                target: employe_login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider  # Utilisation correcte du fournisseur
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_EMPLOYE, ROLE_VETERINAIRE]
        ROLE_EMPLOYE: [ROLE_EMPLOYE]
        ROLE_VETERINAIRE: [ROLE_VETERINAIRE]

    access_control:
    - { path: ^/admin/veterinaire/super, roles: ROLE_SUPER_ADMIN }
    - { path: ^/employe-admin, roles: ROLE_EMPLOYE }
    - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

