vich_uploader:
    db_driver: orm
    mappings:
        user_profile_image:
            uri_prefix: /uploads/profile
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_uploads_images:
            uri_prefix: /uploadsUsers/imagesUsers
            upload_destination: '%kernel.project_dir%/public/uploadsUsers/imagesUsers'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        animal_uploads_images:
            uri_prefix: /uploadsAnimals/imagesAnimals
            upload_destination: '%kernel.project_dir%/public/uploadsAnimals/imagesAnimals'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        habitat_uploads_images:
            uri_prefix: /uploadsHabitats/imagesHabitats
            upload_destination: '%kernel.project_dir%/public/uploadsHabitats/imagesHabitats'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        services_uploads_images:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        animal_images:
            uri_prefix: /uploads/animal_images
            upload_destination: '%kernel.project_dir%/public/uploads/animal_images'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
