vich_uploader:
    db_driver: orm
    mappings:
        user_profile_image:
            uri_prefix: /uploads/profile
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
