services:
  symfony_zoo_app:
    image: symfony_zoo_image
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/        

  mysql:
    image: mysql:8.4
    environment:
       MYSQL_ROOT_PASSWORD: root_password
       MYSQL_DATABASE: symfony_zoo_db
       MYSQL_USER: symfo
       MYSQL_PASSWORD: nbvcxw
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: user_password
    ports:
      - "8082:80"  

volumes:
  data:
