services:
  symfony_zoo_app:
    image: symfony_zoo_image
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
     - .:/var/www
     - cache:/var/www/html/var/cache
     - ./var/log:/var/www/var/log 
    

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_zoo_db
      MYSQL_USER: symfo
      MYSQL_PASSWORD: nbvcxw
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/wal
      - loki_data:/loki
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_DATABASE_HOST=mysql:33:06
      - GF_DATABASE_NAME=symfony_zoo_db
      - GF_DATABASE_USER=symfo
      - GF_DATABASE_PASSWORD=nbvcxw
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - loki
      - prometheus
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  data:
  loki_data:
  grafana_data:
  mysql_data:
  cache: {} 

networks:
  monitoring:
    driver: bridge

    