apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  labels:
    app: symfony-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
      - name: symfony-app
        image: symfony_zoo_image  # Image que tu as définie dans Docker Compose
        ports:
        - containerPort: 80
        volumeMounts:
        - name: symfony-app-code
          mountPath: /var/www/
      volumes:
      - name: symfony-app-code
        hostPath:
          path: /Users/limay/Desktop/CLASSROOM_DEV/SITES_WDM4/SYMFONY/zooparadis  # Adapte ce chemin selon ton besoin
