controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

