<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD45vHEw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD45vHEw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD45vHEw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD45vHEw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD45vHEw\App_KernelDevDebugContainer([
    'container.build_hash' => 'D45vHEw',
    'container.build_id' => 'f4a1a874',
    'container.build_time' => 1725627548,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD45vHEw');
